### ISSUE TITLE
Wide Unicode characters on all platforms

### ISSUE THREAD

**Issue by DanielSWolf** [mobilexag/cordova-sqlite-evplus-ext-free#20]
All platforms (Android, iOS, Windows/UWP, and Browser) should support the full Unicode character range. This includes wide Unicode characters, that is, characters outside the BMP ([Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane)).

For instance, it should be possible to store and retrieve the following string on all platforms: `"This is a test: 😀😉🤪"`

**Comment by DanielSWolf** [comment]
Internal ticket: https://yt.mobilexag.de/issue/PRDXMIP-1033

Old ID: 19.3 (wide Unicode characters)

**Comment by brody2consult** [comment]
This should have been fixed by merged PR #17 on Android, should not be a problem on any of the other platforms.

I think we should be able to close this one as fixed.

Please feel free to comment here or raise new issues in case of any issues with the 4-byte (wide) UTF-8 characters. Part of long-term warranty/support/update plan (#24).

**Comment by brody2consult** [comment]
Closing now. Please report in case of any further issues with the 4-byte (wide) UTF-8 characters on Android (or any other platform).
